version: "3.9"

services:

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
     MYSQL_ROOT_PASSWORD: "mysql"
     MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysqlVol:/var/lib/mysql
      - ${PWD}/../mysql_data/:/mysql_data

  redis:
    image: redis:5
    restart: always
    ports:
      - "6379:6379"

  python3:
    image: python:3.9
    build:
      context: ./python3
    restart: always
    working_dir: /code
    command: tail -f /dev/null
    volumes:
      - ${PWD}/code:/code
    environment:
      - LC_ALL=C.UTF-8
    links:
      - mysql
      - redis
volumes:
  mysqlVol: